### ISSUE TITLE
Can't rebuild working teamviewer image with teamviewer 12

### ISSUE THREAD

**Issue by AnianZ** [hurricanehrndz/docker-containers#11]
If I try to rebuild the docker image for teamviewer it builds and starts up fine, but the GUI never appears. If I look at the logs or run it with `docker run -it` it just stops at `Launching TeamViewer GUI ...`

I really like the this docker image and how it's constructed. The makefile is really nice. But I need teamviewer 12 and can't get it to work.

Log:
```
Cleaning up stopped teamviewer instances...
Starting teamviewer...

Init...
Checking setup...
err:ole:CoGetClassObject class {4315d437-5b8c-11d0-bd3b-00a0c911ce86} not registered
err:ole:CoGetClassObject class {4315d437-5b8c-11d0-bd3b-00a0c911ce86} not registered
err:ole:CoGetClassObject no class object {4315d437-5b8c-11d0-bd3b-00a0c911ce86} could be created for context 0x3
wine: configuration in '/opt/teamviewer/profile' has been updated.
Launching TeamViewer ...
Starting network process (no daemon)
Network process started (459)
Launching TeamViewer GUI ...
```

**Comment by AnianZ** [comment]
I can get it to work, if I drop back to the initial commit in the repo, rebuild and change the `APP_REPO` variable in the start script.

**Comment by hurricanehrndz** [comment]
I will take any pull request as long it is reasonable.

**Comment by AnianZ** [comment]
I will see if I can make out the issue and get it to work :)

**Comment by hurricanehrndz** [comment]
Thanks, I was under the impression that the build from the first commit
works??

**Comment by AnianZ** [comment]
Yes. I'm currently diffing that against the current version to find out what's causing it 🤔

**Comment by kevincaradant** [comment]
I have exactly the same error. Your PR is it ready or "not starting" as the name let me to hear ? 

Thank you :)
