### ISSUE TITLE
GUI never starts

### ISSUE THREAD

**Issue by TerkiKerel** [hurricanehrndz/docker-containers#14]
Hi,

I run these commands:
```
XAUTH=/tmp/.docker.xauth
touch ${XAUTH}
xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f ${XAUTH} nmerge -
docker run -d -e DISPLAY \
    -e XAUTHORITY=${XAUTHORITY} \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    hurricane/teamviewer
```
But there is no any log inside docker (docker logs --follow). I waited 6 minutes. Nothing is printed o console. 

Can you please help me.

Thank you

**Comment by hurricanehrndz** [comment]
Sorry, for the delay, but for which container?

**Comment by jackTaw88** [comment]
I got exactly same issue. 

container: hurricane/teamviewer
OS: ubuntu 18.04
container platform: docker

**Comment by hurricanehrndz** [comment]
Follow this example:
https://github.com/hurricanehrndz/docker-containers/tree/master/tmm
