### ISSUE TITLE
Latest Subsonic docker does not work.  Broken in builds.

### ISSUE THREAD

**Issue by madfusker** [hurricanehrndz/docker-containers#16]

**Comment by hurricanehrndz** [comment]
I no longer use subsonic, so I no longer supported. Sorry for the inconvenience.

**Comment by madfusker** [comment]
Alright, appreciate your response.  1M+ pulls, so a bunch of us loved your repo when it was going and your downloads lead everyone in the world of subsonic!  Yours just worked while the others are junk.

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=subsonic&starCount=0

Ping me if you decided to maintain it again someday. Lately it's barely even been a release once a year at best, lol.  Best regards.

**Comment by hurricanehrndz** [comment]
If that is the case I will try and have a look this week and see what I can
do.
